<?php

namespace CardBundle\Repository;

/**
 * SellerCardRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerCardRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
