<?php

namespace CardBundle\Repository;

/**
 * UserCardRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCardRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
