card_test:
    path:     /test
    defaults: { _controller: "CardBundle:Card:test" }
    methods:  GET
card_index:
    path:     /
    defaults: { _controller: "CardBundle:Card:index" }
    methods:  [GET, POST]

card_show:
    path:     /{id}/show
    defaults: { _controller: "CardBundle:Card:show" }
    methods:  GET

card_new:
    path:     /new
    defaults: { _controller: "CardBundle:Card:new" }
    methods:  [POST]

card_edit:
    path:     /{id}/edit
    defaults: { _controller: "CardBundle:Card:edit" }
    methods:  [PATCH]

card_delete:
    path:     /{id}/delete
    defaults: { _controller: "CardBundle:Card:delete" }
    methods:  DELETE
