<?php

namespace AppBundle\Repository;

/**
 * CardImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardImageRepository extends \Doctrine\ORM\EntityRepository
{
}
