# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    card_bundle.card_service:
        class:         CardBundle\Services\CardService
        arguments:
            - "@doctrine"
            - "@validator"
            - "@=service('security.token_storage').getToken().getUser()"
    card_bundle.seller_service:
        class:         CardBundle\Services\SellerService
        arguments:
            - "@doctrine"
            - "@validator"
    login_bundle.login_service:
        class:         LoginBundle\Services\LoginService
        arguments:
            - "@security.authorization_checker"
            - "@service_container"
            - "@doctrine"
            - "@validator"