login_signin:
    path     : /signin
    defaults : {_controller: "LoginBundle:Login:signin"}
    methods  : POST 

login_signup:
    path     : /signup
    defaults : { _controller: "LoginBundle:Login:signup"}
    methods  : POST

login_signout:
    path     : /signout
    defaults : { _controller: "LoginBundle:Login:signout"}
    methods  : ["GET", "POST"]